# Generated by Django 2.2 on 2020-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='idi',
            field=models.IntegerField(default=0),
        ),
    ]
